### ISSUE TITLE
Failed Update due to missing dependency 

### ISSUE THREAD

**Issue by eddiem5** [mpatfield/homebridge-flume#11]
### What issue do you have? Please be as thorough and explicit as possible.
Failed update to the latest version due to a missing dependency.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS?

Hoobs

* Which version of Homebridge/HOOBS do you have?

Hoobs 4.2.5

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

PI and Node.js is 16.15.1

* Which version of this plugin (homebridge-flume) do you have? Has the issue started since upgrading from a previous version?

2.0.3 - yes since the upgrade

* Which Flume devices do you have that are causing issues? Please include product models if applicable.

F2000

### Please paste any relevant logs below.

```
6/18/2022, 9:47:15 AMFlume Bridge starting
6/18/2022, 9:47:18 AMFlume BridgeERRORError loading plugin "homebridge-flume"
6/18/2022, 9:47:18 AMFlume BridgeERRORCannot find module 'mime-db'
Require stack:
- /var/lib/hoobs/flumebridge/node_modules/mime-types/index.js
- /var/lib/hoobs/flumebridge/node_modules/form-data/lib/form_data.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/defaults/env/FormData.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/defaults/index.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/core/transformData.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/core/dispatchRequest.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/core/Axios.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/axios.js
6/18/2022, 9:47:18 AMFlume BridgeERRORError: Cannot find module 'mime-db'
Require stack:
- /var/lib/hoobs/flumebridge/node_modules/mime-types/index.js
- /var/lib/hoobs/flumebridge/node_modules/form-data/lib/form_data.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/defaults/env/FormData.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/defaults/index.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/core/transformData.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/core/dispatchRequest.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/core/Axios.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/axios.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/lib/hoobs/flumebridge/node_modules/mime-types/index.js:15:10)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/lib/hoobs/flumebridge/node_modules/form-data/lib/form_data.js:9:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
6/18/2022, 9:47:18 AMFlume BridgeWARNINGNo plugins installed.
6/18/2022, 9:47:18 AMFlume BridgeLoading 1 platforms...
6/18/2022, 9:47:18 AMFlume BridgeFailed to find plugin to handle accessory Flume
6/18/2022, 9:47:18 AMFlume BridgeBridge is running on port 51876.
6/18/2022, 9:47:18 AMFlume BridgeWARNINGunhandled rejection: Error: Cannot find module 'mime-db'
Require stack:
- /var/lib/hoobs/flumebridge/node_modules/mime-types/index.js
- /var/lib/hoobs/flumebridge/node_modules/form-data/lib/form_data.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/defaults/env/FormData.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/defaults/index.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/core/transformData.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/core/dispatchRequest.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/core/Axios.js
- /var/lib/hoobs/flumebridge/node_modules/axios/lib/axios.js
```

**Comment by bwp91** [comment]
Hi @eddiem5 
This is a strange one.
Have you tried reinstalling the plug-in to the bridge?
