### ISSUE TITLE
429 Request failed

### ISSUE THREAD

**Issue by FTI76** [mpatfield/homebridge-flume#3]
### What issue do you have? Please be as thorough and explicit as possible.

This is new setup so maybe I need to wait - Maybe its a flume side issue.

[1/11/2022, 5:19:38 PM] [Flume] ***** Disabling plugin. *****
[1/11/2022, 5:19:38 PM] [Flume] ***** [HTTP getDevices()] Request failed with status code 429 at connectionHTTP.getDevices (/usr/lib/node_modules/homebridge-flume/lib/connection/http.js:200:15). *****

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS?

Homebridge w Config UI

* Which version of Homebridge/HOOBS do you have?

1.3.9 

Node.js Version | v16.13.1

* Which version of this plugin (homebridge-flume) do you have? Has the issue started since upgrading from a previous version?

homebridge-flume v1.2.3

* Which Flume devices do you have that are causing issues? Please include product models if applicable.

Flume V2

### Please paste any relevant logs below.

I removed access token stuff.

[1/11/2022, 5:31:42 PM] [Flume] [HTTP obtainToken()] {"success":true,"code":602,"message":"Request OK","http_code":200,"http_message":"OK","detailed":null,"data":[{"token_type":"bearer","access_token":""count":1,"pagination":null}.
[1/11/2022, 5:31:42 PM] [Flume] ***** Disabling plugin. *****
[1/11/2022, 5:31:42 PM] [Flume] ***** [HTTP getDevices()] Request failed with status code 429 at connectionHTTP.getDevices (/usr/lib/node_modules/homebridge-flume/lib/connection/http.js:200:15). *****

**Comment by bwp91** [comment]
Hi @FTI76 

Status code 429 generally means too many requests to the flume system:

https://flumetech.readme.io/docs/rate-limiting

The plugin has been designed to not go over this limit for normal use. Maybe you're not even getting this anymore?

**Comment by FTI76** [comment]
Ben - It’s working now I’m thinking it had to do with something on their end still getting configured when the device was activated maybe.

You can close this one - Thanks!

--
"It's such a fine line between stupid and clever" - David St. Hubbins
