### ISSUE TITLE
2 different errors in logs

### ISSUE THREAD

**Issue by PappyChappy1** [mpatfield/homebridge-flume#49]
### What issue do you have? Please be as thorough and explicit as possible.
Errors in log - 2 different ones, one is ECONNRESET and one is status code 500

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS?

Homebridge

* Which version of Homebridge/HOOBS do you have?

Latest 1.6.0

* Which version of this plugin (homebridge-flume) do you have? Has the issue started since upgrading from a previous version?

Latest stable 2.0.9

* Which Flume devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```
[30/01/2023, 21:05:49] [myQ] myQ API: Successfully connected to the myQ API.
[30/01/2023, 21:19:16] [Flume] [Flume] could not be refreshed as read ECONNRESET at Function.AxiosError.from (file:///var/lib/homebridge/node_modules/homebridge-flume/node_modules/axios/lib/core/AxiosError.js:89:14).
[30/01/2023, 22:11:17] [Flume] [Flume] could not be refreshed as read ECONNRESET at Function.AxiosError.from (file:///var/lib/homebridge/node_modules/homebridge-flume/node_modules/axios/lib/core/AxiosError.js:89:14).
[30/01/2023, 23:36:13] [Flume] [Flume] could not be refreshed as read ECONNRESET at Function.AxiosError.from (file:///var/lib/homebridge/node_modules/homebridge-flume/node_modules/axios/lib/core/AxiosError.js:89:14).
[30/01/2023, 23:49:12] [Flume] [Flume] could not be refreshed as read ECONNRESET at Function.AxiosError.from (file:///var/lib/homebridge/node_modules/homebridge-flume/node_modules/axios/lib/core/AxiosError.js:89:14).
[31/01/2023, 01:10:24] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[31/01/2023, 02:46:54] [Rachio] Expecting webhook authentication
[31/01/2023, 03:36:04] [Flume] [Flume] could not be refreshed as Request failed with status code 500 at settle (file:///var/lib/homebridge/node_modules/homebridge-flume/node_modules/axios/lib/core/settle.js:19:12).
[31/01/2023, 05:49:41] [Homebridge UI] Running scheduled instance backup...
```

**Comment by bwp91** [comment]
Hi @PappyChappy1 

if you are still using this plugin, or whether you can try again, can you confirm if you are still receiving this error message?

Thanks and sorry for the delay in replying to your ticket here 🙂

**Comment by PappyChappy1** [comment]
I installed the update and now every minute I’m seeing this message in my logs -[10/03/2023, 19:53:58] [Flume] [HTTP getLeakInfo()] {"success":true,"code":602,"message":"Request OK","http_code":200,"http_message":"OK","detailed":null,"data":[{"active":false}],"count":1,"pagination":null}.On Mar 10, 2023, at 7:09 PM, Ben ***@***.***> wrote:﻿
Hi @PappyChappy1
if you are still using this plugin, or whether you can try again, can you confirm if you are still receiving this error message?
Thanks and sorry for the delay in replying to your ticket here 🙂

**Comment by bwp91** [comment]
ah great at least it isn’t an error message,
will try to fix the logging issue now 👍🏻

**Comment by bwp91** [comment]
Please check 3.0.1 that it does not log this every minute!

**Comment by PappyChappy1** [comment]
Looking good now thank you!On Mar 10, 2023, at 7:09 PM, Ben ***@***.***> wrote:﻿
Hi @PappyChappy1
if you are still using this plugin, or whether you can try again, can you confirm if you are still receiving this error message?
Thanks and sorry for the delay in replying to your ticket here 🙂

**Comment by bwp91** [comment]
🚀
