### ISSUE TITLE
Error Code 400

### ISSUE THREAD

**Issue by PappyChappy1** [mpatfield/homebridge-flume#58]
What issue do you have? Please be as thorough and explicit as possible.

New error that recently started showing up - error code 400

Details of your setup.

Do you use Homebridge (with config-ui?) or HOOBS?
Homebridge

Which version of Homebridge/HOOBS do you have?
Latest 1.6.0

Which version of this plugin (homebridge-flume) do you have? Has the issue started since upgrading from a previous version?
Latest stable 3.0.1

Which Flume devices do you have that are causing issues? Please include product models if applicable.
Please paste any relevant logs below.

[15/03/2023, 13:57:25] [Flume] [Flume] could not be refreshed as [HTTP renewToken()] Request failed with status code 400 at default.renewToken (file:///var/lib/homebridge/node_modules/homebridge-flume/lib/connection/http.js:162:13).
[15/03/2023, 13:58:25] [Flume] [Flume] could not be refreshed as [HTTP renewToken()] Request failed with status code 400 at default.renewToken (file:///var/lib/homebridge/node_modules/homebridge-flume/lib/connection/http.js:162:13).
[15/03/2023, 13:59:25] [Flume] [Flume] could not be refreshed as [HTTP renewToken()] Request failed with status code 400 at default.renewToken (file:///var/lib/homebridge/node_modules/homebridge-flume/lib/connection/http.js:162:13).

**Comment by harryfrishberg** [comment]
I'm getting the same message.

**Comment by bwp91** [comment]
Hi @PappyChappy1 and @harryfrishberg 

do you have all the necessary credentials configured in the plugin config?

**Comment by PappyChappy1** [comment]
The error actually went away on its own

**Comment by harryfrishberg** [comment]
My error disappeared this morning as well! I wonder if there was some issue on Flume's end? Either way, thanks for the quick reply @bwp91 and excellent work on the great plugin!
